name: trading-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ta-lib
  - pip:
    - fastapi>=0.100.0
    - uvicorn[standard]>=0.23.0
    - pydantic==2.6.1
    - pydantic-settings==2.2.0
    - sqlalchemy[asyncio]>=2.0.0
    - asyncpg==0.29.0
    - alembic==1.13.1
    - redis==5.0.1
    - influxdb-client==1.40.0
    - psycopg2-binary>=2.9.0
    - aiosqlite>=0.19.0
    - celery==5.3.6
    - aio-pika==9.4.1
    - asyncio-mqtt==0.16.1
    - pandas==2.2.0
    - numpy==1.26.4
    - scipy==1.12.0
    - scikit-learn==1.4.0
    - ccxt==4.2.25
    - websockets==12.0
    - aiohttp==3.9.3
    - tensorflow==2.15.0
    - torch==2.2.0
    - optuna==3.5.0
    - transformers==4.37.2
    - ta==0.11.0
    - backtrader==1.9.78.123
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-multipart==0.0.7
    - prometheus-client==0.20.0
    - structlog==24.1.0
    - loguru==0.7.2
    - opentelemetry-api==1.22.0
    - opentelemetry-sdk==1.22.0
    - opentelemetry-instrumentation-fastapi==0.43b0
    - pytest==8.0.0
    - pytest-asyncio==0.23.5
    - pytest-cov==4.0.0
    - black==24.2.0
    - isort==5.13.2
    - mypy==1.8.0
    - python-dotenv==1.0.1
    - click==8.1.7
    - rich==13.7.0
    - docker==7.0.0
    - kubernetes==29.0.0
    - gunicorn==21.2.0
    - psutil==5.9.6 
    - jinja2==3.1.2 
    - python-ngrok==0.1.0 
    - python-dateutil==2.8.2 
    - requests==2.31.0 
    - cryptography==42.0.2 
    - aiodns==3.1.1 
    - yarl==1.9.4